<?php
$KeyUser = $_SESSION['KeyUser'];
?>
<style>
#myProgress {
  width: 100%;
  background-color: #ddd;
}

#myBar {
  width: 1%;
  height: 30px;
  background-color: #4CAF50;
  text-align: center;
  line-height: 30px;
  color: white;
}
</style>	
<!--
<div class="modal fade" id="FormUpload" tabindex="-1" aria-labelledby="FormUpload" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered modal-xl">
<div class="modal-content">
<div class="modal-header bg-dark text-white">
<h5 class="modal-title">Import .ForAlexa file to repository</h5>
<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span style="color: white" aria-hidden="true">&times;</span></button>
</div>

<div class="modal-body">

<form id="uploadForm">
<div class="form-group files">
<label>Upload Your File </label>

<input name="Upload" type="file" class="form-control" id="Upload" accept=".ForAlexa">
<input name="idRepository" type="hidden" id="idRepository" value="5">
<input name="KeyUser" type="hidden" id="KeyUser" value="">	

<button id="BtnUpload" type="button" class="btn btn-lg btn-success">Import ForAlexa File</button>	
</div>

</form>
   
<div id="myProgress"><div class="progress-bar progress-bar-striped progress-bar-animated" id="myBar">Upload File</div></div>

	
<div id="ProcessingFile"><div class="text-center"><h2>Processing ForAlexa File....</h2></div><img src="https://cdn.dribbble.com/users/171267/screenshots/2454901/fileloading.gif" width="50%"><div class="text-center"><h3>Please wait....</h3></div></div>	
	
</div>
</div>
</div>
-->
<div class="modal fade" tabindex="-1" id="Consult">
<div class="modal-dialog modal-dialog-centered">
<div class="modal-content">
<div class="modal-header bg-light text-dark">
<h5 class="modal-title mx-auto">Loading Database</h5>
</div>
<div class="modal-body text-center">		
	
<div class="loadingio-spinner-double-ring-1erlfmkoj4g"><div class="ldio-whak2g63h6">
<div></div>
<div></div>
<div><div></div></div>
<div><div></div></div>
</div></div>
<style type="text/css">
@keyframes ldio-whak2g63h6 {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-whak2g63h6 div { box-sizing: border-box!important }
.ldio-whak2g63h6 > div {
  position: absolute;
  width: 140px;
  height: 140px;
  top: 30px;
  left: 30px;
  border-radius: 50%;
  border: 20px solid #000;
  border-color: #120a8f transparent #120a8f transparent;
  animation: ldio-whak2g63h6 1s linear infinite;
}

.ldio-whak2g63h6 > div:nth-child(2), .ldio-whak2g63h6 > div:nth-child(4) {
  width: 96px;
  height: 96px;
  top: 52px;
  left: 52px;
  animation: ldio-whak2g63h6 1s linear infinite reverse;
}
.ldio-whak2g63h6 > div:nth-child(2) {
  border-color: transparent #120a8f transparent #120a8f
}
.ldio-whak2g63h6 > div:nth-child(3) { border-color: transparent }
.ldio-whak2g63h6 > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-whak2g63h6 > div:nth-child(3) div:before, .ldio-whak2g63h6 > div:nth-child(3) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 20px;
  height: 20px;
  top: -20px;
  left: 40px;
  background: #120a8f;
  border-radius: 50%;
  box-shadow: 0 120px 0 0 #120a8f;
}
.ldio-whak2g63h6 > div:nth-child(3) div:after {
  left: -20px;
  top: 40px;
  box-shadow: 120px 0 0 0 #120a8f;
}

.ldio-whak2g63h6 > div:nth-child(4) { border-color: transparent; }
.ldio-whak2g63h6 > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-whak2g63h6 > div:nth-child(4) div:before, .ldio-whak2g63h6 > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 20px;
  height: 20px;
  top: -20px;
  left: 18px;
  background: #120a8f;
  border-radius: 50%;
  box-shadow: 0 76px 0 0 #120a8f;
}
.ldio-whak2g63h6 > div:nth-child(4) div:after {
  left: -20px;
  top: 18px;
  box-shadow: 76px 0 0 0 #120a8f;
}
.loadingio-spinner-double-ring-1erlfmkoj4g {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-whak2g63h6 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-whak2g63h6 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>	
		
</div>
<div class="modal-footer">Please wait...</div>	
</div>
</div>
</div>


<div class="row row-cols-1 justify-content-sm-center mt-3">
 
<div class="col mb-3 ">
<div class="card">
<div class="card-header">Hello <?php echo($_SESSION['FirstName']);?> <?php echo($_SESSION['LastName']);?></div>	
<div class="card-body">
<div class="row row-cols-1 justify-content-sm-center">
	
<div class="col-sm-6 mb-5 mt-5">
<h5 class="card-title"><?php echo($NewRepository);?></h5>
<a href="index.php?p=NewRepository&Action=CDS" class="btn btn-primary btn-lg"><i class="fas fa-4x fa-plus"></i></a>
</div>

<!--
<div class="col-sm-6 mb-5 mt-5">
<h5 class="card-title">Download Skill Examples</h5>
<div><a class="btn btn-lg btn-primary mb-3" href="#" role="button">Example 1</a></div>
<div><a class="btn btn-lg btn-primary mt-3" href="#" role="button">Example 2</a></div>	
</div>	
-->
	
</div>	
	
</div>
<?php
$search 	= mysqli_query($mysqli, "SELECT * FROM Repository WHERE KeyUser = '$KeyUser'");
$num_rows 	= mysqli_num_rows($search);	
?>
<div class="card-footer text-muted">You Have <b><?php echo($num_rows); ?></b> of <b>5</b> Repositories</div>	
</div>
</div>
</div>	

<div class="row row-cols-1 justify-content-sm-center">
<?php
$KeyUser = $_SESSION['KeyUser'];
$query = "SELECT * FROM `Repository` WHERE KeyUser = '$KeyUser'";
$result = $mysqli->query($query);
while ($row = $result->fetch_assoc()){	
?>		
	
<div class="col-sm-2 mb-3">
<div class="card">
<div class="card-header"><?php echo($row["RepositoryName"]);?></div>	
<div class="card-body">
<p class="card-text"><?php echo($row["Description"]);?></p>
<button type="button" class="btn btn-success" id="<?php echo("id_".$row["idRepository"]);?>" onClick="return confirm('Access Repository <?php echo($row["RepositoryName"]);?> ?');"><i class="fas fa-external-link-alt"></i></button>
	
<!--
<button id="btnForm" value="<?php //echo($row["idRepository"]);?>" type="button" class="btn btn-info" data-toggle="modal" data-target="#FormUpload"><i class="fas fa-file-import"></i></button>	
	
<a href="CSV.php?idRepository=<?php //echo($row["idRepository"]);?>&KeyUser=<?php //echo($row["KeyUser"]);?>" class="btn btn-warning"><i class="fas fa-download"></i></a>	
-->
<a href="index.php?p=NewRepository&Action=Update&idRepository=<?php echo($row["idRepository"]);?>&KeyUser=<?php echo($row["KeyUser"]);?>" class="btn btn-primary" onClick="return confirm('Edit Repository <?php echo($row["RepositoryName"]);?> ?');"><i class="fas fa-edit"></i></a>
<a href="index.php?p=CDSNewRepository&Action=Delete&idRepository=<?php echo($row["idRepository"]);?>&KeyUser=<?php echo($row["KeyUser"]);?>" class="btn btn-danger" onClick="return confirm('Delete Repository <?php echo($row["RepositoryName"]);?> ?');"><i class="fas fa-trash-alt"></i></a>	
</div>
<div class="card-footer text-muted text-center">
<p>Expires on <?php $DateBD = date_create($row["DateCreation"]); date_add($DateBD, date_interval_create_from_date_string('91 days')); $DateFormated = date_format($DateBD, 'Y/m/d'); echo($DateFormated);?></p>
<p><?php						  
$date1 = date_create("now");
$date2 = $DateBD;
$interval = $date1->diff($date2); 
echo $interval->days . " days remaining";									   
?></p>
</div>	
</div>
</div>



<script>
var KeyUser = '<?php echo($KeyUser); ?>';
	
$('#<?php echo("id_".$row["idRepository"]);?>').click(function() {
$('#Consult').modal('show');	
var <?php echo("idRepository_".$row['KeyUser']);?> = "<?php echo($row['idRepository']);?>";
$.ajax({ 		
url: 'Verification.php', 
type: 'POST', 
data:{"KeyUser" : KeyUser, "idRepository" : <?php echo($row['idRepository']);?>}, 
success: function(data) { 
console.log(data); 
if(data == 1){	
location.href = 'index.php?p=IntentList&idRepository='+<?php echo("idRepository_".$row['KeyUser']);?>+'&KeyUser='+KeyUser;
} else {

}	
}});
}); 

</script>
<?php } ?>
</div>	

<script>	
//var idRepository = "5";	
//var KeyUser = "dOKvyVbIBkLasxNuynNYEytkqCnxlzXllaEgcnsDyjNjZuIwGB";
//$('#myProgress').hide();
//$('#ProcessingFile').hide();	
//$('#BtnUpload').click(function(event) {
//$('#myProgress').show();	
//var i = 0;
//if (i == 0) {
//i = 1;
//var elem = document.getElementById("myBar");
//var width = 1;
//var id = setInterval(frame, 1);
//function frame() {
//if (width >= 100) {
//clearInterval(id);
//i = 0;
//} else {
//width++;
//elem.style.width = width + "%";
//}}}	
//$('.myProgress').hide('slow').delay(5000);	
	
//$('#uploadForm').hide('slow').delay(9000);

//$('#ProcessingFile').show('slow');
	
//event.preventDefault();	
//$.ajax({ 		
//url: 'ReadCSV.php', 
//type: 'POST', 
//data:{"KeyUser" : KeyUser, "idRepository" : idRepository }, 
//contentType:false,
//cache:false,
//processData:false,	
//success: function(data) { 
//data = $.parseJSON(data);
//alert("Intents Processed: " + data.Intents + " | Intents Stored Repository: "+ data.IntentsInsert);	
//location.href = 'index.php?p=IntentList&idRepository='+idRepository+'&KeyUser='+KeyUser;
//}});
//}); 

//$('#BtnUpload').click(function() {
//
	
//
//$.ajax({	
//type: 'POST',
//url: 'ReadCSV.php',
//data:{"KeyUser" : KeyUser, "idRepository" : idRepository}, 
//	
//success: function(response) {
////data = $.parseJSON(response);
//$('#ProcessingFile').hide('slow');	
//
//},
//});
//});	
//	
//// File type validation
//$("#Upload").change(function(){
//var regexp;	
//var extension = uploadForm.Upload.value.substr(uploadForm.Upload.value.lastIndexOf('.'));	
//if ((extension.toLowerCase() != ".foralexa")){
//alert('Please select a valid file (.ForAlexa).');
//$("#Upload").val('');
//return false;	
//}	
//});

</script>