<div id="ErrorLogin">		
<div class="alert alert-danger alert-dismissible" role="alert">
<div><?php echo($ErrorLogin);?></div>
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
</div>


<div class="modal fade" tabindex="-1" id="FormLoading">
<div class="modal-dialog modal-dialog-centered">
<div class="modal-content">
<div class="modal-header bg-light text-dark">
<h5 class="modal-title mx-auto"><?php echo($FAL);?></h5>
</div>
<div class="modal-body text-center">		
<div>	
<div class="loadingio-spinner-bean-eater-rmydrbgmg5"><div class="ldio-entgl9wkzda">
<div><div></div><div></div><div></div></div><div><div></div><div></div><div></div></div>
</div></div>
<style type="text/css">
@keyframes ldio-entgl9wkzda-1 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(-45deg) }
  100% { transform: rotate(0deg) }
}
@keyframes ldio-entgl9wkzda-2 {
    0% { transform: rotate(180deg) }
   50% { transform: rotate(225deg) }
  100% { transform: rotate(180deg) }
}
.ldio-entgl9wkzda > div:nth-child(2) {
  transform: translate(-15px,0);
}
.ldio-entgl9wkzda > div:nth-child(2) div {
  position: absolute;
  top: 40px;
  left: 40px;
  width: 120px;
  height: 60px;
  border-radius: 120px 120px 0 0;
  background: #eeb440;
  animation: ldio-entgl9wkzda-1 1s linear infinite;
  transform-origin: 60px 60px
}
.ldio-entgl9wkzda > div:nth-child(2) div:nth-child(2) {
  animation: ldio-entgl9wkzda-2 1s linear infinite
}
.ldio-entgl9wkzda > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}@keyframes ldio-entgl9wkzda-3 {
    0% { transform: translate(190px,0); opacity: 0 }
   20% { opacity: 1 }
  100% { transform: translate(70px,0); opacity: 1 }
}
.ldio-entgl9wkzda > div:nth-child(1) {
  display: block;
}
.ldio-entgl9wkzda > div:nth-child(1) div {
  position: absolute;
  top: 92px;
  left: -8px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #290908;
  animation: ldio-entgl9wkzda-3 1s linear infinite
}
.ldio-entgl9wkzda > div:nth-child(1) div:nth-child(1) { animation-delay: -0.67s }
.ldio-entgl9wkzda > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33s }
.ldio-entgl9wkzda > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
.loadingio-spinner-bean-eater-rmydrbgmg5 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-entgl9wkzda {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-entgl9wkzda div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style></div>	
	
		
</div>
</div>
</div>
</div>

<div class="text-center text-white"><h1>Login</h1></div>
<div class="row mt-3 justify-content-sm-center">
<div class="col-sm-6"><button class="btn btn-lg btn-block btn-dark LoginC" type="button" data-toggle="collapse" data-target="#LoginC" aria-expanded="false" aria-controls="LoginC">Login with Email</button></div>
<!--<div class="col-sm-5"><button class="btn btn-lg btn-block btn-dark Social" type="button" data-toggle="collapse" data-target="#Social" aria-expanded="false" aria-controls="Social">Social Media (beta)</button></div>-->
</div>

<div class="mx-auto mt-5 mb-5 container collapse" id="LoginC">
<form id="FormLogin">	
<div class="form-group">
<label class="text-white">Email Address</label>	
<div class="input-group mb-5">	
<div class="input-group-prepend">	
<div class="input-group-text"><i class="fas fa-2x fa-at"></i>
</div>
</div>
<input name="Login" type="email" autofocus="autofocus" required="required" class="form-control form-control-lg mx-auto" id="Login" placeholder="<?php echo($LoginEmail);?>" autocomplete="on">
</div>
</div>

<div class="form-group">
<label class="text-white">Password</label>	
<div class="input-group mb-5">	
<div class="input-group-prepend">	
<div class="input-group-text"><i class="fas fa-2x fa-key"></i>
</div>
</div>
<input name="Passs" type="password" required="required" class="form-control form-control-lg mx-auto" id="Passs" placeholder="<?php echo($LoginPass);?>">
</div>
</div>
	
<div><button type="submit" class="btn btn-primary btn-lg btn-block mb-5">Sign In<i class="fas fa-2x fa-sign-in-alt ml-2"></i></button></div>
</form>	

	
<div class="card-footer bg-white text-dark">
<div class="row row-cols-1 justify-content-sm-left mt-1">	
<div class="col-sm-6 mb-1 text-center">Not a ForAlexa member? <a class="btn btn-primary" href="Login.php?p=NewUser" role="button">Sign up ForAlexa</a></div>
<div class="col-sm-6 mb-1 text-center">Forgot your Password? <a class="btn btn-primary" href="Login.php?p=Recover" role="button">Recover Password</a></div>
</div>
</div>	
</div>	

<script>
$(document).ready(function(){
$('#ErrorLogin').hide();
$('#FormLogin').submit(function(){
$('#FormLoading').modal('show'); 
//$("#luan").modal("toggle");
	
// Variáveis Login
var Login =$('#Login').val();
var Passs =$('#Passs').val();

$.ajax({
url:  "OpLogin.php",
type: "POST",
data: {"Login" : Login, "Passs" : Passs},
success: function (result) {
console.log(result);
if(result == 0){	
$('#FormLoading').modal('hide');	
$('#ErrorLogin').show();
} else {
location.href = 'index.php'	
}}});
return false;
})})
</script>

<!--
<div class="mx-auto mt-5 mb-5 container-fluid collapse" id="Social">
<div class="row row-cols-1 justify-content-sm-center">
	
<div class="col-sm-2">
	<button type="button" class="Amazon btn btn-block btn-lg">
	<span><i class="fab fa-2x fa-amazon mr-2 ml-2 mt-2 mb-2"></i></span>	
	Amazon
	</button>
</div>
	
<div class="col-sm-2 mb-2 mt-2"><button type="button" class="Facebook btn btn-block btn-lg"><div><i class="fab fa-2x fa-facebook mr-2"></i>Facebook</button></div>
<div class="col-sm-2 mb-2 mt-2"><button type="button" class="Twitter btn btn-block btn-lg"><div><i class="fab fa-2x fa-twitter mr-2"></i>Twitter</button></div>	
<div class="col-sm-2 mb-2 mt-2"><button type="button" class="Google btn btn-block btn-lg"><div><i class="fab fa-2x fa-google mr-2"></i>Google</button></div>	
<div class="col-sm-2 mb-2 mt-2"><button type="button" class="Microsoft btn btn-block btn-lg"><div><i class="fab fa-2x fa-microsoft mr-2"></i>Microsoft</button></div>					
</div>		
</div>	
-->

	
<script>
$(document).ready(function(){
$(".LoginC").click(function(){
$("#Social").collapse('hide');
$("#LoginC").collapse('show');	
});
$(".Social").click(function(){
$("#LoginC").collapse('hide');
$("#Social").collapse('show');	
});	
});
</script>	